import sys
import os
import struct

def main():
    if len(sys.argv) < 4:
        print("Usage: spv_to_h.py <input.spv> <output.h> <base_name>")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    # Sanitize the file name to create a valid C++ variable name
    var_name = sys.argv[3].replace('.', '_').replace('-', '_')

    # Read binary bytes
    with open(input_path, 'rb') as f:
        data = f.read()

    # Ensure data length aligns to 4-byte SPIR-V words
    if len(data) % 4 != 0:
        raise ValueError("SPIR-V file size must be a multiple of 4 bytes.")

    # Unpack binary data into 32-bit unsigned integers
    words = struct.unpack(f'<{len(data) // 4}I', data)

    # Write the C++ header file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("// Auto-generated by spv_to_h.py\n")
        f.write("#pragma once\n\n")
        f.write("#include \"common/types.h\"\n\n")
        f.write(f"alignas(4) const u32 {var_name}_data[] = {{\n    ")
        
        for i, word in enumerate(words):
            f.write(f"0x{word:08X}, ")
            if (i + 1) % 6 == 0:
                f.write("\n    ")
                
        f.write(f"\n}};\n\n")
        f.write(f"const std::size_t {var_name}_size = sizeof({var_name}_data) / 4;\n")

if __name__ == '__main__':
    main()