// SPDX-FileCopyrightText: Copyright 2026 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#version 460

#extension GL_EXT_shared_memory_block : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_memory_scope_semantics : require

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_shader_atomic_int64 : require
#extension GL_KHR_shader_subgroup_vote : require

struct WarpMem {
    uint a[MAX_NUM_WAVES];
    uint b[MAX_NUM_WAVES];
};

layout(std430) shared shared_mem_ordered_count
{
    layout (offset = SHARED_MEMORY_BASE_OFFSET)
    uint wave_counts[MAX_NUM_WAVES];

    // used by barrier
    shared uint communication_mem_u32[MAX_NUM_WAVES];

    // used by readfirstlane/ballot/barrier to synchronize
    shared uint barrier_mem[MAX_NUM_WAVES];

    shared WarpMem warp_mem[2];

    uint scratch_val;
};

struct Counter {
    uint next_writer;
    uint global_count;
};

layout(std430, set = 0, binding = UTILITY_BUFFER_BINDING) buffer ordered_count_utility
{
    uint next_emulated_workgroup_index;
    // TODO play with offsets for cache opts
    Counter counters[NUM_COUNTERS];
};

void init_shared_mem() {
    // TODO
    if (gl_LocalInvocationIndex < MAX_NUM_WAVES) {
        communication_mem_u32[gl_LocalInvocationIndex] = 0;
        barrier_mem[gl_LocalInvocationIndex] = 0;

        warp_mem[0].a[gl_LocalInvocationIndex] = 0;
        warp_mem[0].b[gl_LocalInvocationIndex] = 0;
        warp_mem[1].a[gl_LocalInvocationIndex] = 0;
        warp_mem[1].b[gl_LocalInvocationIndex] = 0;
    }
}

uint get_wave_id() {
    return gl_LocalInvocationIndex / 64;
}

uint get_lane_id() {
    return gl_LocalInvocationIndex % 64;
}

void wave_barrier_subgroup32() {
    uint wave_id = get_wave_id();
    bool first = 0 == atomicXor(communication_mem_u32[wave_id], 1, 
                                                                gl_ScopeWorkgroup,
                                                                gl_StorageSemanticsShared, // Should this also be for buffer memory etc?
                                                                gl_SemanticsAcquireRelease);
    if (!first) {
        atomicStore(barrier_mem[wave_id], 1u,
                                        gl_ScopeWorkgroup,
                                        gl_StorageSemanticsShared,
                                        gl_SemanticsRelease); // TODO volatile? check others
    } else {
        for (;;) {
            if (1u == atomicCompSwap(barrier_mem[wave_id], 1u, 0u,
                                                        gl_ScopeWorkgroup,
                                                        gl_StorageSemanticsShared,
                                                        gl_SemanticsVolatile | gl_SemanticsRelease,
                                                        gl_StorageSemanticsNone,
                                                        gl_SemanticsVolatile | gl_SemanticsRelaxed)) {  // TODO what is point of semequal???
                break;
            }
        }
    }
}

bool elect_subgroup32_workgroupsync(bool is_active) {
    const uint wave_id = get_wave_id();
    const bool any = subgroupAny(is_active);
    const bool is_warp_0 = (gl_SubgroupID & 1) == 0;

    bool elected = is_active && subgroupElect();

    if (is_warp_0 && subgroupElect()) {
        warp_mem[0].a[wave_id] = any ? 1 : 0;
    }
    barrier();
    if (!is_warp_0 && elected) {
        elected = warp_mem[0].a[wave_id] == 0;
    }
    barrier();

    return elected;
}

// TODO let IR decide this
bool elect_generic(bool is_active) {
    if (gl_SubgroupSize == 32) {
#if 0
        return elect_subgroup32(is_active);
#else
        return elect_subgroup32_workgroupsync(is_active);
#endif
    } else {
        // assume 64
        return is_active && subgroupElect();
    }
}

uint readfirstlane_subgroup32_workgroupsync(uint value, bool is_active) {
    const uint wave_id = get_wave_id();
    const bool any = subgroupAny(is_active);
    const uint lane = any ? subgroupBallotFindLSB(subgroupBallot(is_active)) : 0;
    const bool elected = gl_SubgroupInvocationID == lane;
    const uint subgroup_in_wave = gl_SubgroupID & 1;
    const bool is_bottom = subgroup_in_wave == 0;

    uint rval;

    if (elected) {
        warp_mem[subgroup_in_wave].a[wave_id] = value;
        warp_mem[subgroup_in_wave].b[wave_id] = is_active ? 1 : 0;
    }
    barrier();
    if (elected) {
        const uint other_value = warp_mem[subgroup_in_wave ^ 1].a[wave_id];
        const bool other_active = warp_mem[subgroup_in_wave ^ 1].b[wave_id] == 1;
        if (is_bottom) {
            rval = (is_active || !other_active) ? value : other_value;
        } else {
            rval = (is_active && !other_active) ? value : other_value;
        }
    }
    barrier();

    return subgroupBroadcast(rval, lane);
}

// TODO let IR decide this
uint readfirstlane_generic(uint value, bool is_active) {
    if (gl_SubgroupSize == 32) {
#if 0
        return readfirstlane_subgroup32(value, is_active);
#else
        return readfirstlane_subgroup32_workgroupsync(value, is_active);
#endif
    } else {
        // assume 64
        uint lane = subgroupAny(is_active) ? subgroupBallotFindLSB(subgroupBallot(is_active)) : 0;
        return subgroupBroadcast(value, lane);
    }
}

uvec2 wave_ballot_subgroup32_workgroupsync(bool value) {
    const uint wave_id = get_wave_id();
    const uint subgroup_in_wave = gl_SubgroupID & 1;
    const bool is_bottom = subgroup_in_wave == 0;

    const uint my_ballot = subgroupBallot(value).x;
    warp_mem[subgroup_in_wave].a[wave_id] = my_ballot;
    barrier();
    const uint other_ballot = warp_mem[subgroup_in_wave ^ 1].a[wave_id];
    barrier();

    return is_bottom ? uvec2(my_ballot, other_ballot) : uvec2(other_ballot, my_ballot);
}

// TODO let IR decide this
uvec2 wave_ballot_generic(bool value) {
    if (gl_SubgroupSize == 32) {
#if 0
        return wave_ballot_subgroup32(value);
#else
        return wave_ballot_subgroup32_workgroupsync(value);
#endif
    } else {
        // assume 64
        return subgroupBallot(value).xy;
    }
}

// Grab a workgroup index by bumping a counter used by all dispatched workgroups.
// This is to guarantee forward progress in a shader that uses DS_ORDERED_COUNT,
// because workgroups aren't dispatched in particular order according to the actual
// gl_WorkgroupId, but each workgroup must wait for all lower-numbered ones to be counted.
// Could break in theory if workgroups can be unscheduled until higher numbered finishes
// ie deadlock
uint init_emulated_workgroup_index() {
#if 1
    // TODO call from main
    init_shared_mem();
#endif

    if (gl_LocalInvocationIndex == 0) {
        scratch_val = atomicAdd(next_emulated_workgroup_index, 1);
    }
    barrier();
    return scratch_val;
}

uint get_num_waves() {
    uint wg_size = gl_WorkGroupSize.x * gl_WorkGroupSize.y * gl_WorkGroupSize.z;
    return (wg_size + 63) / 64;
}

uint get_global_wave_index(uint workgroup_index) {
    uint wave_id = get_wave_id();
    uint num_waves = get_num_waves();

    return workgroup_index * num_waves + wave_id;
}

uint ordered_count_add_per_wave(uint workgroup_index, uint packer_id, uint value, bool is_active)
{
    uint prev_count = 0;

    // TODO can there be no active threads?
#if 1
    bool elected = elect_generic(is_active);
#else
    // Hack for GOW because this is placed inside exec-divergent branch
    // currently (but only one thread active anyways in what Ive seen)
    bool elected = is_active;
#endif

    if (elected) {
        uint wave_index = get_global_wave_index(workgroup_index);

        for (;;) {
            uint next_writer = atomicLoad(counters[packer_id].next_writer, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsAcquire);
            if (next_writer == wave_index) {
                break;
            }
        }

        prev_count = atomicAdd(counters[packer_id].global_count, value);
        atomicStore(counters[packer_id].next_writer, wave_index + 1, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease);
    }

    // TODO do this part in IR
    return readfirstlane_generic(prev_count, is_active);
}

uint ordered_count_swap_per_wave(uint workgroup_index, uint packer_id, uint value, bool is_active)
{
    uint prev_count = 0;

    // TODO can there be no active threads?
#if 1
    bool elected = elect_generic(is_active);
#else
    bool elected = is_active;
#endif

    if (elected) {
        uint wave_index = get_global_wave_index(workgroup_index);

        for (;;) {
            uint next_writer = atomicLoad(counters[packer_id].next_writer, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsAcquire);
            if (next_writer == wave_index) {
                break;
            }
        }

        prev_count = atomicExchange(counters[packer_id].global_count, value);
        atomicStore(counters[packer_id].next_writer, wave_index + 1, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease);
    }

    // TODO do this part in IR
    return readfirstlane_generic(prev_count, is_active);
}

uint ordered_count_add_workgroupsync(uint workgroup_index, uint packer_id, uint value, bool is_active) {
    uint wave_id = get_wave_id();
    uint num_waves = get_num_waves();

    // TODO can there be no active threads?
    bool elected = elect_generic(is_active);

    if (elected) {
        // should only be 1 thread per wave here
        wave_counts[wave_id] = value;
    }

    barrier();

    // host subgroup size must be >= number of guest waves per workgroup for this to work
    if (gl_SubgroupID == 0) {
        const uint my_count = gl_LocalInvocationIndex < num_waves
                ? wave_counts[gl_LocalInvocationIndex]
                : 0;

        uint my_scan = subgroupExclusiveAdd(my_count);

        if (gl_LocalInvocationIndex < num_waves)
        {
            wave_counts[gl_LocalInvocationIndex] = my_scan;
        }
    }

    barrier();

    if (elected && wave_id == num_waves - 1) {
        uint workgroup_count = value + wave_counts[wave_id];

        for (;;) {
            uint next_writer = atomicLoad(counters[packer_id].next_writer, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsAcquire);
            if (next_writer == workgroup_index) {
                break;
            }
        }

        uint prev_count = atomicAdd(counters[packer_id].global_count, workgroup_count);
        atomicStore(counters[packer_id].next_writer, workgroup_index + 1, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease);
        scratch_val = prev_count;
    }

    barrier();

    return scratch_val + wave_counts[wave_id];
}